### ISSUE TITLE
Feature suggestion: Add custom attributes to input. 

### ISSUE THREAD

**Issue by NordicAngel** [opensass/input-rs#7]
As someone new to Yew, I thank you for this crate, it makes inputs a lot easier.

That said how about a way of adding extra attributes, to the input html tag. Lets say i would like to make a `datalist` input that would need me to use the `list` attribute or I want to add a `onchange` event to the input. 

I would suggest a way of taking one or more arbitrary attribute and add them to the `input` tag. 

I hope you will consider my suggestion, I'm not sure how difficult it would be as I'm not yet very experienced in Rust as a whole.

**Comment by wiseaidev** [comment]
Thanks for filing this issue, @NordicAngel. Awesome feature! Let's see if I can ship a new release today.

**Comment by wiseaidev** [comment]
Done! I decided to add support for all major wasm frameworks as well: yew, dioxus and leptos!
